UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 126808;
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 126158;
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 122324;
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 122159;
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 51712;
UPDATE `gameobject_template` SET `ScriptName`='go_legion_communicator' WHERE  `entry`=244440;
UPDATE `creature_template` SET `ScriptName`='npc_40618_artifact' WHERE  `entry`=102478;
UPDATE `creature_template` SET `ScriptName`='npc_thrall_965270' WHERE  `entry`=96527;
UPDATE `gameobject_template` SET `ScriptName`='go_highborne_203213' WHERE  `entry`=203213;
UPDATE `gameobject_template` SET `ScriptName`='go_highborne_203218' WHERE  `entry`=203218;
UPDATE `gameobject_template` SET `ScriptName`='go_highborne_203212' WHERE  `entry`=203212;
UPDATE `creature_template` SET `ScriptName`='npc_glowing_sentry_100525' WHERE  `entry`=100525;
UPDATE `creature_template` SET `ScriptName`='npc_glowing_sentry_120300' WHERE  `entry`=120300;
UPDATE `creature_template` SET `ScriptName`='boss_tirathon_saltheril' WHERE  `entry`=95885;
UPDATE `creature_template` SET `ScriptName`='npc_tirathon_beam_target' WHERE  `entry`=96241;
UPDATE `creature_template` SET `ScriptName`='npc_glayvianna_soulrender' WHERE  `entry`=98177;
UPDATE `creature_template` SET `ScriptName`='npc_drelanim' WHERE  `entry`=103860;
UPDATE `creature_template` SET `ScriptName`='boss_inquisitor_tormentorum' WHERE  `entry`=96015;
UPDATE `creature_template` SET `ScriptName`='boss_glazer' WHERE  `entry`=99865;
UPDATE `creature_template` SET `ScriptName`='npc_glazer_beam' WHERE  `entry`=102310;
UPDATE `creature_template` SET `ScriptName`='npc_glazer_lens' WHERE  `entry`=98082;
UPDATE `creature_template` SET `ScriptName`='boss_ashgolm' WHERE  `entry`=95886;
UPDATE `creature_template` SET `ScriptName`='npc_ashgolm_ember' WHERE  `entry`=99233;
UPDATE `creature_template` SET `ScriptName`='npc_ashgolm_countermeasures' WHERE  `entry`=99240;
UPDATE `creature_template` SET ScriptName = 'npc_lunaclaw_spirit' WHERE entry = 12144;
UPDATE creature_template SET scriptname = 'npc_warl_shadowy_tear' WHERE entry = 99887;
UPDATE creature_template SET scriptname = 'npc_warl_chaos_tear' WHERE entry = 108493;
UPDATE creature_template SET ScriptName='npc_timothy_daniels' WHERE entry=18019;
UPDATE `creature_template` SET `ScriptName`='npc_mortog_steamhead' WHERE `entry`=23373;
UPDATE `creature_template` SET `ScriptName`='mob_netherweb_victim' WHERE `entry`=22355;
UPDATE `creature_template` SET `ScriptName`='npc_Scion_of_Ice_106701' WHERE  `entry`=106701;
UPDATE `creature_template` SET `ScriptName`='npc_Scion_of_fire_106700' WHERE  `entry`=106700;
UPDATE `creature_template` SET `ScriptName`='npc_Scion_of_Magic_106702' WHERE  `entry`=106702;
UPDATE `creature_template` SET `ScriptName`='npc_warden_alturas_vh' WHERE  `entry`=99473;
UPDATE `creature_template` SET `ScriptName`='npc_portal_bunny' WHERE `entry`='105204';
UPDATE `creature_template` SET `ScriptName` = 'npc_illidari_felbat_99227' WHERE `entry` = 99227;
UPDATE `gameobject_template` SET `ScriptName`='go_aldrachi_warblades_248785' WHERE  `entry`=248785;
UPDATE `creature_template` SET `ScriptName`='npc_caria_felsoul_99184' WHERE  `entry`=99184;
UPDATE `creature_template` SET `ScriptName`='npc_aldrachi_revenant_105151' WHERE  `entry`=105151;
UPDATE `creature_template` SET `ScriptName`='npc_gorgonnash_99046' WHERE  `entry`=99046;
UPDATE `creature_template` SET `ScriptName`='npc_doomherald_taraar_105094' WHERE  `entry`=105094;
UPDATE `creature_template` SET `ScriptName`='npc_doomherald_saera_105095' WHERE  `entry`=105095;
UPDATE `gameobject_template` SET `ScriptName`='go_brokenshore_felsoul_portal' WHERE `entry` IN (248573, 248517);
UPDATE `gameobject_template` SET `ScriptName`='go_temporary_allari_cage' WHERE  `entry`=266029;
UPDATE `creature_template` SET `ScriptName`='npc_allari_souleater_98882' WHERE  `entry`=98882;
UPDATE `gameobject_template` SET `ScriptName`='go_the_scythe_of_elune_246437' WHERE  `entry`=246437;
UPDATE `creature_template` SET `ScriptName`='npc_ariden_102200' WHERE  `entry`=102200;
UPDATE `gameobject_template` SET `ScriptName`='go_cavern_stones_7796' WHERE  `entry`=245045;
UPDATE `gameobject_template` SET `ScriptName` = 'go_the_scythe_of_elune_1' WHERE `entry` = 246436;
UPDATE `creature_template` SET `ScriptName` = 'npc_the_conservator_101257' WHERE `entry` = 101257; 
UPDATE `creature_template` SET `ScriptName` = 'npc_ariden_100850' WHERE `entry` = 100850;
UPDATE `creature_template` SET `ScriptName` = 'npc_revil_kost_101282' WHERE `entry` = 101282;
UPDATE `creature_template` SET `ScriptName` = 'npc_ebonfang_108115' WHERE `entry` = 108115;
UPDATE `gameobject_template` SET `Data1`=250386, `ScriptName`='go_fangs_of_ashamane' WHERE `entry`= 250386 ;
UPDATE `creature_template` SET `ScriptName` = 'npc_verstok_darkbough_108053' WHERE `entry` = 108053;
UPDATE `creature_template` SET `ScriptName` = 'npc_webmistress_shinaris_108027' WHERE `entry` = 108027;
UPDATE `creature_template` SET `ScriptName` = 'npc_verstok_darkbough_108003' WHERE `entry` = 108003;
UPDATE `creature_template` SET `ScriptName` = 'npc_clear_platform_107937' WHERE `entry` = 107937;
UPDATE `gameobject_template` SET `ScriptName` = 'go_ruined_switch' WHERE `entry` = 250638;
UPDATE `gameobject_template` SET `ScriptName` = 'go_platform' WHERE `entry` = 250824;
UPDATE `creature_template` SET `ScriptName` = 'npc_ravenous_withered_107790' WHERE `entry` = 107790;
UPDATE `gameobject_template` SET `ScriptName` = 'go_g_hanir_1' WHERE `entry` = 248499;
UPDATE `creature_template` SET `ScriptName` = 'npc_destromath_104619' WHERE `entry` = 104619;
UPDATE `creature_template` SET `ScriptName` = 'npc_lyessa_bloomwatcher_104628' WHERE `entry` = 104628;
UPDATE `creature_template` SET `ScriptName` = 'npc_archdruid_hamuul_runetotem_104659' WHERE `entry` = 104659;
UPDATE `creature_template` SET `ScriptName` = 'npc_celestine_of_the_harvest_104657' WHERE `entry` = 104657;
UPDATE `creature_template` SET `ScriptName` = 'npc_zen_tabra_104658' WHERE `entry` = 104658;
UPDATE `creature_template` SET `ScriptName` = 'npc_skylord_omnuron_104620' WHERE `entry` = 104620;
UPDATE `instance_template` SET `Script` = 'scenario_artifact_restoacqusition' WHERE `map` = 1599;
UPDATE `gameobject_template` SET `ScriptName` = 'go_claws_of_ursoc_248853' WHERE `entry` = 248853;
UPDATE `creature_template` SET `ScriptName`='npc_lea_stonepaw_105243' WHERE `entry`=105243;
UPDATE `gossip_menu_option` SET  `OptionType`=1, `OptionNpcFlag`=1 WHERE `MenuId`=19156 ;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_spirit_of_ursoc_101362' WHERE `entry`=101362;
UPDATE `creature_template` SET `InhabitType`=4, `ScriptName`='npc_claws_of_ursoc_105331' WHERE `entry`=105331;
UPDATE `creature_template` SET `ScriptName`='npc_mylune_101393' WHERE `entry`=101393;
UPDATE `creature_template` SET `ScriptName`='npc_shade_of_xavius_101403' WHERE `entry`=101403;
UPDATE `creature_template` SET `ScriptName`='npc_lea_stonepaw_101742' WHERE `entry`=101742;
UPDATE `creature_template` SET `ScriptName`='npc_verdant_warder_101754' WHERE `entry`=101754;
UPDATE `creature_template` SET `ScriptName`='npc_lea_stonepaw_101743' WHERE `entry`=101743;
UPDATE `creature_template` SET `ScriptName` = 'npc_alodi_102846' WHERE `entry` = 102846;
UPDATE `creature_template` SET `ScriptName` = 'npc_forge_of_the_guardian_102786' WHERE `entry` = 102786;
UPDATE `creature_template` SET `ScriptName` = 'npc_siphoning_rift_102787' WHERE `entry` = 102787;
UPDATE `creature_template` SET `ScriptName` = 'npc_meryl_felstorm_102850' WHERE `entry` = 102850;
UPDATE `creature_template` SET `ScriptName` = 'npc_kathra_natir_102785' WHERE `entry` = 102785;
UPDATE `creature_template` SET `ScriptName`='npc_decaying_minion' WHERE  `entry`=114568;
UPDATE `creature_template` SET `ScriptName`='npc_grimelord' WHERE  `entry`=114709;
UPDATE `creature_template` SET `ScriptName`='npc_cordana_glowing_sentry' WHERE  `entry`=100525;
UPDATE `creature_template` SET `ScriptName`='npc_cordana_spirit_of_vengeance' WHERE  `entry`=100364;
UPDATE `creature_template` SET `ScriptName`='npc_bilewater_slime' WHERE  `entry`=116195;
UPDATE `creature_template` SET `ScriptName`='npc_gripping_tentacle' WHERE  `entry`=114900;