-- by Sargero
DELETE FROM `scene_template` WHERE `SceneId`=3000;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3000, 0, 1893, '');
DELETE FROM `scene_template` WHERE `SceneId`=3001;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3001, 0, 1894, '');
DELETE FROM `scene_template` WHERE `SceneId`=3002;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3002, 0, 1902, '');
DELETE FROM `scene_template` WHERE `SceneId`=3003;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3003, 0, 1908, '');
DELETE FROM `scene_template` WHERE `SceneId`=3004;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3004, 0, 1911, '');
DELETE FROM `scene_template` WHERE `SceneId`=3005;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3005, 0, 1919, '');
DELETE FROM `scene_template` WHERE `SceneId`=3006;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3006, 0, 1924, '');
DELETE FROM `scene_template` WHERE `SceneId`=3007;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3007, 0, 1925, '');
DELETE FROM `scene_template` WHERE `SceneId`=3008;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3008, 0, 1938, '');
DELETE FROM `scene_template` WHERE `SceneId`=3009;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3009, 0, 1953, '');
DELETE FROM `scene_template` WHERE `SceneId`=3010;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3010, 0, 1960, '');
DELETE FROM `scene_template` WHERE `SceneId`=3011;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3011, 0, 1968, '');
DELETE FROM `scene_template` WHERE `SceneId`=3012;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3012, 0, 1973, '');
DELETE FROM `scene_template` WHERE `SceneId`=3013;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3013, 0, 1985, '');
DELETE FROM `scene_template` WHERE `SceneId`=3014;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3014, 0, 1988, '');
DELETE FROM `scene_template` WHERE `SceneId`=3015;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3015, 0, 1989, '');
DELETE FROM `scene_template` WHERE `SceneId`=3016;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3016, 0, 1994, '');
DELETE FROM `scene_template` WHERE `SceneId`=3017;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3017, 0, 1996, '');
DELETE FROM `scene_template` WHERE `SceneId`=3018;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3018, 0, 1997, '');
DELETE FROM `scene_template` WHERE `SceneId`=3019;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3019, 0, 1998, '');
DELETE FROM `scene_template` WHERE `SceneId`=3020;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3020, 0, 2001, '');
DELETE FROM `scene_template` WHERE `SceneId`=3021;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3021, 0, 2002, '');
DELETE FROM `scene_template` WHERE `SceneId`=3022;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3022, 0, 2009, '');
DELETE FROM `scene_template` WHERE `SceneId`=3023;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3023, 0, 2010, '');
DELETE FROM `scene_template` WHERE `SceneId`=3024;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3024, 0, 2023, '');
DELETE FROM `scene_template` WHERE `SceneId`=3025;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3025, 0, 2028, '');
DELETE FROM `scene_template` WHERE `SceneId`=3026;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3026, 0, 2032, '');
DELETE FROM `scene_template` WHERE `SceneId`=3027;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3027, 0, 2042, '');
DELETE FROM `scene_template` WHERE `SceneId`=3028;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3028, 0, 2043, '');
DELETE FROM `scene_template` WHERE `SceneId`=3029;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3029, 0, 2044, '');
DELETE FROM `scene_template` WHERE `SceneId`=3030;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3030, 0, 2045, '');
DELETE FROM `scene_template` WHERE `SceneId`=3031;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3031, 0, 2046, '');
DELETE FROM `scene_template` WHERE `SceneId`=3032;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3032, 0, 2047, '');
DELETE FROM `scene_template` WHERE `SceneId`=3033;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3033, 0, 2048, '');
DELETE FROM `scene_template` WHERE `SceneId`=3034;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3034, 0, 2049, '');
DELETE FROM `scene_template` WHERE `SceneId`=3035;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3035, 0, 2050, '');
DELETE FROM `scene_template` WHERE `SceneId`=3036;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3036, 0, 2054, '');
DELETE FROM `scene_template` WHERE `SceneId`=3037;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3037, 0, 2055, '');
DELETE FROM `scene_template` WHERE `SceneId`=3038;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3038, 0, 2058, '');
DELETE FROM `scene_template` WHERE `SceneId`=3039;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3039, 0, 2059, '');
DELETE FROM `scene_template` WHERE `SceneId`=3040;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3040, 0, 2060, '');
DELETE FROM `scene_template` WHERE `SceneId`=3041;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3041, 0, 2061, '');
DELETE FROM `scene_template` WHERE `SceneId`=3042;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3042, 0, 2062, '');
DELETE FROM `scene_template` WHERE `SceneId`=3043;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3043, 0, 2063, '');
DELETE FROM `scene_template` WHERE `SceneId`=3044;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3044, 0, 2065, '');
DELETE FROM `scene_template` WHERE `SceneId`=3045;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3045, 0, 2069, '');
DELETE FROM `scene_template` WHERE `SceneId`=3046;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3046, 0, 2071, '');
DELETE FROM `scene_template` WHERE `SceneId`=3047;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3047, 0, 2074, '');
DELETE FROM `scene_template` WHERE `SceneId`=3048;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3048, 0, 2084, '');
DELETE FROM `scene_template` WHERE `SceneId`=3049;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3049, 0, 2085, '');
DELETE FROM `scene_template` WHERE `SceneId`=3050;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3050, 0, 2087, '');
DELETE FROM `scene_template` WHERE `SceneId`=3051;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3051, 0, 2089, '');
DELETE FROM `scene_template` WHERE `SceneId`=3052;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3052, 0, 2094, '');
DELETE FROM `scene_template` WHERE `SceneId`=3053;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3053, 0, 2098, '');
DELETE FROM `scene_template` WHERE `SceneId`=3054;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3054, 0, 2102, '');
DELETE FROM `scene_template` WHERE `SceneId`=3055;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3055, 0, 2104, '');
DELETE FROM `scene_template` WHERE `SceneId`=3056;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3056, 0, 2105, '');
DELETE FROM `scene_template` WHERE `SceneId`=3057;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3057, 0, 2106, '');
DELETE FROM `scene_template` WHERE `SceneId`=3058;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3058, 0, 2145, '');
DELETE FROM `scene_template` WHERE `SceneId`=3059;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3059, 0, 2147, '');
DELETE FROM `scene_template` WHERE `SceneId`=3060;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3060, 0, 2148, '');
DELETE FROM `scene_template` WHERE `SceneId`=3061;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3061, 0, 2149, '');
DELETE FROM `scene_template` WHERE `SceneId`=3062;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3062, 0, 2150, '');
DELETE FROM `scene_template` WHERE `SceneId`=3063;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3063, 0, 2151, '');
DELETE FROM `scene_template` WHERE `SceneId`=3064;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3064, 0, 2152, '');
DELETE FROM `scene_template` WHERE `SceneId`=3065;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3065, 0, 2155, '');
DELETE FROM `scene_template` WHERE `SceneId`=3066;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3066, 0, 2161, '');
DELETE FROM `scene_template` WHERE `SceneId`=3067;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3067, 0, 2162, '');
DELETE FROM `scene_template` WHERE `SceneId`=3068;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3068, 0, 2185, '');
DELETE FROM `scene_template` WHERE `SceneId`=3069;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3069, 0, 2190, '');
DELETE FROM `scene_template` WHERE `SceneId`=3070;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3070, 0, 2191, '');
DELETE FROM `scene_template` WHERE `SceneId`=3071;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3071, 0, 2200, '');
DELETE FROM `scene_template` WHERE `SceneId`=3072;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3072, 0, 2299, '');
DELETE FROM `scene_template` WHERE `SceneId`=3073;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3073, 0, 2300, '');
DELETE FROM `scene_template` WHERE `SceneId`=3074;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3074, 0, 2301, '');
DELETE FROM `scene_template` WHERE `SceneId`=3075;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3075, 0, 2302, '');
DELETE FROM `scene_template` WHERE `SceneId`=3076;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3076, 0, 2304, '');
DELETE FROM `scene_template` WHERE `SceneId`=3077;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3077, 0, 2307, '');
DELETE FROM `scene_template` WHERE `SceneId`=3078;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3078, 0, 2309, '');
DELETE FROM `scene_template` WHERE `SceneId`=3079;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3079, 0, 2315, '');
DELETE FROM `scene_template` WHERE `SceneId`=3080;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3080, 0, 2316, '');
DELETE FROM `scene_template` WHERE `SceneId`=3081;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3081, 0, 2317, '');
DELETE FROM `scene_template` WHERE `SceneId`=3082;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3082, 0, 2323, '');
DELETE FROM `scene_template` WHERE `SceneId`=3083;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3083, 0, 2326, '');
DELETE FROM `scene_template` WHERE `SceneId`=3084;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3084, 0, 2329, '');
DELETE FROM `scene_template` WHERE `SceneId`=3085;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3085, 0, 2330, '');
DELETE FROM `scene_template` WHERE `SceneId`=3086;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3086, 0, 2331, '');
DELETE FROM `scene_template` WHERE `SceneId`=3087;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3087, 0, 2342, '');
DELETE FROM `scene_template` WHERE `SceneId`=3088;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3088, 0, 2344, '');
DELETE FROM `scene_template` WHERE `SceneId`=3089;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3089, 0, 2350, '');
DELETE FROM `scene_template` WHERE `SceneId`=3090;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3090, 0, 2351, '');
DELETE FROM `scene_template` WHERE `SceneId`=3091;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3091, 0, 2353, '');
DELETE FROM `scene_template` WHERE `SceneId`=3092;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3092, 0, 2356, '');
DELETE FROM `scene_template` WHERE `SceneId`=3093;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3093, 0, 2357, '');
DELETE FROM `scene_template` WHERE `SceneId`=3094;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (3094, 0, 2359, '');