-- fix quest 11636
delete from `smart_scripts` where `entryorguid`=2546000;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2546000','9','0','0','0','0','100','0','1000','1000','0','0','11','45603','0','0','0','0','0','23','0','0','0','0','0','0','0','Amazing Carpet - Cast Ride Carpet on summoner');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2546000','9','1','0','0','0','100','0','100','100','0','0','53','0','25460','0','0','0','0','1','0','0','0','0','0','0','0','Amazing Carpet - Load waypath');

UPDATE `smart_scripts` SET `action_type`=85 WHERE `entryorguid`=25459 AND `id`=0;

delete from `smart_scripts` where `entryorguid`=2546001;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2546001','9','0','0','0','0','100','0','0','0','0','0','15','11636','0','0','0','0','0','23','0','0','0','0','0','0','0','Amazing Carpet - Give quest credit');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2546001','9','1','0','0','0','100','0','500','500','0','0','28','45602','0','0','0','0','0','23','0','0','0','0','0','0','0','Amazing Carpet - Remove aura 45602');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2546001','9','2','0','0','0','100','0','100','100','0','0','28','46598','0','0','0','0','0','23','0','0','0','0','0','0','0','Amazing Carpet - Remove aura 46598');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2546001','9','3','0','0','0','100','0','200','200','0','0','41','200','0','0','0','0','0','1','0','0','0','0','0','0','0','Amazing Carpet - Despawn');
