/*
SQLyog Community
MySQL - 5.6.47-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('140826','0','0','Fell for it!','14','0','100','0','0','0','0','0','Thistlebrush Sprite to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('139678','0','0','Grgl...','12','0','100','0','0','0','0','0','Shoal-Walker to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('136834','0','0','Ya gonna watch me eat ya!','12','0','100','0','0','0','0','0','Scalper Bazuulu to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('136834','1','0','Ugh... ya got me...','12','0','100','0','0','0','0','0','Scalper Bazuulu to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('134997','0','0','You ain\'t seen... the last of me...','12','0','100','0','0','104039','0','0','Gazlowe to Gazlowe');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('130871','0','0','Don\'t blink, Alliance.','14','0','100','0','0','104056','0','0','Skaggit to Skaggit');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('72704','0','0','%s goes into a frenzy!','16','0','100','0','0','0','0','0','Dragonflayer Metalworker');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('25422','0','0','Who disturbs my meditation?!','14','0','100','0','0','0','0','0','High Priest Talet-Kha to Mystical Webbing');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('25378','0','0','What is the meaning of this?! I have not yet finished my feast!','14','0','100','0','0','0','0','0','High Priest Naferset to En\'kilah Necromancer');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('23472','0','0','%s moves up the tunnel!','41','0','100','0','0','0','0','0','Hadronox to World Trigger (Large AOI, Not Immune PC/NPC)');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('17252','0','0','Attention all units, $r inside the perimeter.','12','0','100','0','0','0','0','0','Sentry-bot 57-K to 17252');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('106848','0','0','Activate counter-measures. Repel intruder.','12','0','100','0','0','0','0','0','Sentry-bot 57-K to 106848');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('106848','1','0','Warning: $r incursion detected!','12','0','100','0','0','0','0','0','Sentry-bot 57-K to 106848');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30595','0','0','We shall triumph!','14','0','100','0','0','14882','0','0','Highlord Tirion Fordring');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30595','1','0','The time of the Argent Crusade is now!','14','0','100','0','0','14881','0','0','Highlord Tirion Fordring');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30595','2','0','Have at you, fiends! You shall not escape the wrath of the Ashbringer!','14','0','100','0','0','14822','0','0','Highlord Tirion Fordring to Frostbrood Destroyer');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30639','0','0','Fixin\' the tower and the wall! Keep the baddies off us!','14','0','100','0','0','14561','0','0','Argent Mason to Argent Cannon');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('31264','0','0','You will be alone in the end.','15','0','100','0','0','14372','0','0','A Mysterious Voice to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30385','0','0','I have been chosen!','14','0','100','0','0','14345','0','0','Twilight Volunteer to Jedoga Shadowseeker');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30385','1','0','I give myself to the master!','14','0','100','0','0','14346','0','0','Twilight Volunteer to Jedoga Shadowseeker');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30116','0','0','As the leader of the Sunreavers, it is with great pride that I present $n as the new bearer of Quel\'Delar!','14','0','100','0','0','0','0','0','Archmage Aethas Sunreaver to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('30115','0','0','This is a great day for all who oppose the Lich King! Brave $n has taken up the ancient blade, Quel\'Delar, in the name of the Silver Covenant!','14','0','100','0','0','0','0','0','Vereesa Windrunner to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('28921','0','0','%s moves up the tunnel!','41','0','100','0','0','13941','0','0','Hadronox to World Trigger (Large AOI, Not Immune PC/NPC)');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('27483','0','0','%s raises his talons menacingly!','41','0','100','0','0','0','0','0','King Dred');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('26625','0','0','%s flees back to its den....','16','0','100','0','0','0','0','0','Darkweb Recluse');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('55564','0','0','Anub\'Arak has fallen, my brothers! Rise from the depths and reclaim our birthright!','14','0','100','0','0','14069','0','0','Reclaimer A\'zak to Player');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('55658','0','0','Make haste and secure the area! Much work remains to be done.','14','0','100','0','0','0','0','0','Seer Ixit');
insert into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('55658','1','0','The rebirth of the Empire of Azjol-Nerub is upon us! Hear my call, brothers, and rise to reclaim what is rightfully ours!','14','0','100','0','0','0','0','0','Seer Ixit');
