/*chain of mechagon quest*/
DELETE FROM `creature_template` WHERE `entry`=150208;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `femaleName`, `subname`, `TitleAlt`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `HealthScalingExpansion`, `RequiredExpansion`, `VignetteID`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `family`, `trainer_type`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `HealthModifierExtra`, `ManaModifier`, `ManaModifierExtra`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `FadeRegionRadius`, `WidgetSetID`, `WidgetSetUnitConditionID`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (150208, 0, 0, 0, 0, 0, 'Tinkmaster Overspark', '', 'Chief Architect of Gnomish Engineering', NULL, NULL, 0, 120, 120, 7, 0, 0, 35, 2, 1, 1.14286, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, '', 33528);
DELETE FROM `creature_queststarter` WHERE `id`=150208 AND `quest`=54088;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (150208, 54088);
DELETE FROM `creature_questender` WHERE `id`=149864 AND `quest`=54088;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (149864, 54088);
DELETE FROM `quest_template_addon` WHERE `ID`=54088;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (54088, 0, 0, 0, 0, 55040, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=149864 AND `quest`=55040;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (149864, 55040);
DELETE FROM `creature_questender` WHERE `id`=149877 AND `quest`=55040;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (149877, 55040);
DELETE FROM `quest_template_addon` WHERE `ID`=55040;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55040, 0, 0, 0, 54088, 54945, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=149877 AND `quest`=54945;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (149877, 54945);
DELETE FROM `creature_questender` WHERE `id`=149877 AND `quest`=54945;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (149877, 54945);
DELETE FROM `quest_template_addon` WHERE `ID`=54945;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (54945, 0, 0, 0, 55040, 54087, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=149877 AND `quest`=54087;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (149877, 54087);
DELETE FROM `creature_questender` WHERE `id`=152864 AND `quest`=54087;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (152864, 54087);
DELETE FROM `quest_template_addon` WHERE `ID`=54087;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (54087, 0, 0, 0, 54945, 54946, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=152864 AND `quest`=54946;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (152864, 54946);
DELETE FROM `creature_questender` WHERE `id`=151100 AND `quest`=54946;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (151100, 54946);
DELETE FROM `quest_template_addon` WHERE `ID`=54946;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (54946, 0, 0, 0, 54087, 54947, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=151100 AND `quest`=54947;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (151100, 54947);
DELETE FROM `creature_questender` WHERE `id`=150145 AND `quest`=54947;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (150145, 54947);
DELETE FROM `quest_template_addon` WHERE `ID`=54947;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (54947, 0, 0, 0, 54946, 54992, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=150145 AND `quest`=54992;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (150145, 54992);
DELETE FROM `creature_questender` WHERE `id`=152482 AND `quest`=54992;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (152482, 54992);
DELETE FROM `quest_template_addon` WHERE `ID`=54992;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (54992, 0, 0, 0, 54947, 55645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=152484 AND `quest`=55645;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (152484, 55645);
DELETE FROM `creature_questender` WHERE `id`=152851 AND `quest`=55645;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (152851, 55645);
DELETE FROM `quest_template_addon` WHERE `ID`=55645;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55645, 0, 0, 0, 54992, 55729, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=152851 AND `quest`=55729;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (152851, 55729);
DELETE FROM `creature_questender` WHERE `id`=152820 AND `quest`=55729;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (152820, 55729);
DELETE FROM `quest_template_addon` WHERE `ID`=55729;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55729, 0, 0, 0, 55645, 55730, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=152820 AND `quest`=55730;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (152820, 55730);
DELETE FROM `creature_questender` WHERE `id`=153670 AND `quest`=55730;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (153670, 55730);
DELETE FROM `quest_template_addon` WHERE `ID`=55730;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55730, 0, 0, 0, 55729, 55731, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=152820 AND `quest`=55731;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (152820, 55731);
DELETE FROM `creature_questender` WHERE `id`=153670 AND `quest`=55731;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (153670, 55731);
DELETE FROM `quest_template_addon` WHERE `ID`=55731;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55731, 0, 0, 0, 55730, 55995, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=150956 AND `quest`=55995;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (150956, 55995);
DELETE FROM `creature_questender` WHERE `id`=153670 AND `quest`=55995;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (153670, 55995);
DELETE FROM `quest_template_addon` WHERE `ID`=55995;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55995, 0, 0, 0, 55731, 55734, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=153670 AND `quest`=55734;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (153670, 55734);
DELETE FROM `creature_questender` WHERE `id`=153670 AND `quest`=55734;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (153670, 55734);
DELETE FROM `quest_template_addon` WHERE `ID`=55734;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55734, 0, 0, 0, 55995, 55736, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
DELETE FROM `creature_queststarter` WHERE `id`=151947 AND `quest`=55736;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (151947, 55736);
DELETE FROM `creature_questender` WHERE `id`=149816 AND `quest`=55736;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (149816, 55736);
DELETE FROM `quest_template_addon` WHERE `ID`=55736;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55736, 0, 0, 0, 55734, 56131, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

DELETE FROM `world_quest` WHERE `id`=56131;
INSERT INTO `world_quest` (`id`, `duration`, `variable`, `value`, `VerifiedBuild`) VALUES (56131, 259200, 16125, 1, 30918);

DELETE FROM `creature_queststarter` WHERE `id`=149816 AND `quest`=55609;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (149816, 55609);
DELETE FROM `creature_questender` WHERE `id`=149816 AND `quest`=55609;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (149816, 55609);
DELETE FROM `quest_template_addon` WHERE `ID`=55609;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES (55609, 0, 0, 0, 55736, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

DELETE FROM `quest_template` WHERE `ID`=54088;
INSERT INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `ScalingFactionGroup`, `MaxScalingLevel`, `QuestPackageID`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `SuggestedGroupNum`, `RewardNextQuest`, `RewardXPDifficulty`, `RewardXPMultiplier`, `RewardMoney`, `RewardMoneyDifficulty`, `RewardMoneyMultiplier`, `RewardBonusMoney`, `RewardDisplaySpell1`, `RewardDisplaySpell2`, `RewardDisplaySpell3`, `RewardSpell`, `RewardHonor`, `RewardKillHonor`, `StartItem`, `RewardArtifactXPDifficulty`, `RewardArtifactXPMultiplier`, `RewardArtifactCategoryID`, `Flags`, `FlagsEx`, `FlagsEx2`, `RewardItem1`, `RewardAmount1`, `RewardItem2`, `RewardAmount2`, `RewardItem3`, `RewardAmount3`, `RewardItem4`, `RewardAmount4`, `ItemDrop1`, `ItemDropQuantity1`, `ItemDrop2`, `ItemDropQuantity2`, `ItemDrop3`, `ItemDropQuantity3`, `ItemDrop4`, `ItemDropQuantity4`, `RewardChoiceItemID1`, `RewardChoiceItemQuantity1`, `RewardChoiceItemDisplayID1`, `RewardChoiceItemID2`, `RewardChoiceItemQuantity2`, `RewardChoiceItemDisplayID2`, `RewardChoiceItemID3`, `RewardChoiceItemQuantity3`, `RewardChoiceItemDisplayID3`, `RewardChoiceItemID4`, `RewardChoiceItemQuantity4`, `RewardChoiceItemDisplayID4`, `RewardChoiceItemID5`, `RewardChoiceItemQuantity5`, `RewardChoiceItemDisplayID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity6`, `RewardChoiceItemDisplayID6`, `POIContinent`, `POIx`, `POIy`, `POIPriority`, `RewardTitle`, `RewardArenaPoints`, `RewardSkillLineID`, `RewardNumSkillUps`, `PortraitGiver`, `PortraitGiverMount`, `PortraitTurnIn`, `RewardFactionID1`, `RewardFactionValue1`, `RewardFactionOverride1`, `RewardFactionCapIn1`, `RewardFactionID2`, `RewardFactionValue2`, `RewardFactionOverride2`, `RewardFactionCapIn2`, `RewardFactionID3`, `RewardFactionValue3`, `RewardFactionOverride3`, `RewardFactionCapIn3`, `RewardFactionID4`, `RewardFactionValue4`, `RewardFactionOverride4`, `RewardFactionCapIn4`, `RewardFactionID5`, `RewardFactionValue5`, `RewardFactionOverride5`, `RewardFactionCapIn5`, `RewardFactionFlags`, `RewardCurrencyID1`, `RewardCurrencyQty1`, `RewardCurrencyID2`, `RewardCurrencyQty2`, `RewardCurrencyID3`, `RewardCurrencyQty3`, `RewardCurrencyID4`, `RewardCurrencyQty4`, `AcceptedSoundKitID`, `CompleteSoundKitID`, `AreaGroupID`, `TimeAllowed`, `AllowableRaces`, `TreasurePickerID`, `Expansion`, `ManagedWorldStateID`, `QuestSessionBonus`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `PortraitGiverText`, `PortraitGiverName`, `PortraitTurnInText`, `PortraitTurnInName`, `QuestCompletionLog`, `VerifiedBuild`) VALUES (54088, 2, -1, 0, 120, 0, 120, 8567, 0, 0, 0, 1, 1, 23400, 1, 1, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 307232768, 8192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 890, 878, 0, 0, 6130900294268439629, 0, 7, 0, 0, 'The Legend of Mechagon', 'Meet Tinkmaster Overspark outside the mysterious vault.', 'I came as soon as I heard!  A mysterious vault has been discovered in Tiragarde. \n\nCenturies ago, the last king of the gnomes, King Mechagon, led his followers in search of a mythical land of technology. He left no clue as to where he was headed, and over time his legend faded into history. This vault could be the first step to discovering King Mechagon\'s true fate! \n\nI must examine it firsthand. Meet me there, Champion. I could use your assistance.', '', '', '', '', '', '', 33528);

DELETE FROM `creature_template` WHERE `entry`=149864;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `femaleName`, `subname`, `TitleAlt`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `HealthScalingExpansion`, `RequiredExpansion`, `VignetteID`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `family`, `trainer_type`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `HealthModifierExtra`, `ManaModifier`, `ManaModifierExtra`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `FadeRegionRadius`, `WidgetSetID`, `WidgetSetUnitConditionID`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (149864, 0, 0, 0, 0, 0, 'Tinkmaster Overspark', '', 'Chief Architect of Gnomish Engineering', NULL, NULL, 0, 120, 120, 7, 0, 0, 35, 2, 1, 1.14286, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 7, 4096, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 10, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, '', 33528);
DELETE FROM `creature` WHERE `guid`=2103360742569;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `phaseUseFlags`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (2103360742569, 152904, 1643, 8567, 10423, '0', 0, 0, 0, -1, 0, 0, -908.469, 122.888, 86.7546, 0.339003, 300, 0, 0, 157, 0, 0, 0, 0, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=2103360742536;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `phaseUseFlags`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (2103360742536, 149864, 1643, 8567, 9638, '0', 0, 0, 0, -1, 0, 0, -903.332, 121.696, 86.7749, 0.731982, 300, 0, 0, 315, 0, 0, 0, 0, 0, 0, 0, '', 0);
DELETE FROM `creature_template` WHERE `entry`=149864;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `femaleName`, `subname`, `TitleAlt`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `HealthScalingExpansion`, `RequiredExpansion`, `VignetteID`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `family`, `trainer_type`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `HealthModifierExtra`, `ManaModifier`, `ManaModifierExtra`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `FadeRegionRadius`, `WidgetSetID`, `WidgetSetUnitConditionID`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (149864, 0, 0, 0, 0, 0, 'Tinkmaster Overspark', '', 'Chief Architect of Gnomish Engineering', NULL, NULL, 0, 120, 120, 7, 0, 0, 35, 2, 1, 1.14286, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 7, 4096, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 10, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, '', 33528);
DELETE FROM `creature_text` WHERE `CreatureID`=149864 AND `GroupID`=0 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149864, 0, 0, 'Look! This is clearly ancient gnomish technology!', 12, 0, 100, 1, 0, 132742, 169267, 0, '');
DELETE FROM `creature_text` WHERE `CreatureID`=149864 AND `GroupID`=1 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149864, 1, 0, 'If we can unlock its secrets, we will surely find Mechagon!', 12, 0, 100, 1, 0, 132744, 169664, 0, '');
DELETE FROM `creature_text` WHERE `CreatureID`=149864 AND `GroupID`=2 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149864, 2, 0, 'Gila, please take notes. I want to record our actions for future study.', 12, 0, 100, 1, 0, 132746, 169893, 0, '');
DELETE FROM `quest_objectives` WHERE `ID`=389416;
INSERT INTO `quest_objectives` (`ID`, `QuestID`, `Type`, `Order`, `StorageIndex`, `ObjectID`, `Amount`, `Flags`, `Flags2`, `ProgressBarWeight`, `Description`, `VerifiedBuild`) VALUES (389416, 54088, 0, 0, 0, 149864, 1, 24, 0, 0, '', 33528);
DELETE FROM `creature_text` WHERE `CreatureID`=149877 AND `GroupID`=0 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149877, 0, 0, 'My fellow tinkologists, we have made a great discovery!', 12, 0, 100, 1, 0, 132745, 169891, 0, '');
DELETE FROM `creature_text` WHERE `CreatureID`=149877 AND `GroupID`=1 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149877, 1, 0, 'The technology in this vault is still intact.', 12, 0, 100, 1, 0, 132747, 169892, 0, '');
DELETE FROM `creature_text` WHERE `CreatureID`=149877 AND `GroupID`=2 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149877, 2, 0, 'If we can unlock its secrets, we will surely find Mechagon!', 12, 0, 100, 0, 0, 132744, 169664, 0, '');
DELETE FROM `creature_text` WHERE `CreatureID`=149877 AND `GroupID`=3 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (149877, 3, 0, 'Now let the examination begin!', 12, 0, 100, 0, 0, 132743, 170897, 0, '');

