-- 9756, What We Don't Know...
UPDATE creature_template SET AIName = 'SmartAI' WHERE entry = 17824;
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (17824, 0, 0, 1, 62, 0, 100, 512, 7533, 0, 0, 0, '', 33, 17974, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Captured Sunhawk Agent - On Gossip Option - Kill Credit');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (17824, 0, 1, 0, 61, 0, 100, 512, 0, 0, 0, 0, '', 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Captured Sunhawk Agent - On Gossip Option - Close Gossip');
-- 938, Mist
UPDATE creature_template SET AIName = 'SmartAI' WHERE entry = 3568;
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (3568, 0, 0, 0, 19, 0, 100, 512, 938, 0, 0, 0, '', 80, 356800, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Mist - On Quest Accepted- Action list');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (3568, 0, 1, 0, 75, 0, 100, 513, 0, 3519, 4, 0, '', 80, 356801, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Mist - Creature distance- Action list');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (3568, 0, 2, 0, 6, 0, 100, 512, 0, 0, 0, 0, '', 6, 938, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 'Mist - On Death - Fail Quest');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (3568, 0, 3, 4, 11, 0, 100, 512, 0, 0, 0, 0, '', 2, 80, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Mist - On Respawn - Set faction');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (3568, 0, 4, 0, 61, 0, 100, 512, 0, 0, 0, 0, '', 8, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Mist - On Respawn - React passive');
INSERT INTO `item_script_names` (`Id`, `ScriptName`) VALUES ('24318', 'item_sample_water_flask_24318');
UPDATE `creature_template` SET `unit_flags`='67108864' WHERE (`entry`='17592');
UPDATE `creature_loot_template` SET `QuestRequired`='0' WHERE (`Entry`='2166') AND (`Item`='8136');
