UPDATE `creature_template` SET `ScriptName`='npc_power_matrix' WHERE (`entry`='134107');
UPDATE `creature_template` SET `ScriptName`='npc_amorphous_cyst' WHERE (`entry`='134034');
UPDATE `creature_template` SET `ScriptName`='npc_cyclopean_terror' WHERE (`entry`='138531');
UPDATE `creature_template` SET `ScriptName`='npc_dark_young' WHERE (`entry`='134635');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('272504', 'spell_explosive_corruption_selector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('274506', 'spell_explosive_corruption');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('270373', 'spell_wave_of_corruption_selector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('269455', 'spell_power_matrix_cast');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265281', 'spell_power_matrix_aura');
UPDATE `areatrigger_template` SET `ScriptName`='areatrigger_undulating_mass' WHERE (`Id`='17350');
UPDATE `areatrigger_template` SET `ScriptName`='areatrigger_undulating_mass' WHERE (`Id`='18108');
UPDATE `areatrigger_template` SET `ScriptName`='areatrigger_blighted_corruption' WHERE (`Id`='17948');
UPDATE `creature_template` SET `ScriptName`='boss_fetid_devourer' WHERE (`entry`='133298');
UPDATE `creature_template` SET `ScriptName`='boss_mythrax' WHERE (`entry`='134546');
UPDATE `creature_template` SET `ScriptName`='npc_plague_amalgam' WHERE (`entry`='135016');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265208', 'spell_gestate_selector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265212', 'spell_gestate');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('276439', 'spell_omega_vector_target_selector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('267160', 'spell_omega_vector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('267161', 'spell_omega_vector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('267162', 'spell_omega_vector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('267163', 'spell_omega_vector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('266459', 'spell_plague_bomb_cast');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('266948', 'spell_plague_bomb');
UPDATE `areatrigger_template` SET `ScriptName`='areatrigger_plague_bomb' WHERE (`Id`='17917');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265370', 'spell_blood_geyser_damage');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265281', 'spell_blood_geyser_aura');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265928', 'spell_blood_geyser_cast');
UPDATE `areatrigger_template` SET `ScriptName`='areatrigger_blood_geyser' WHERE (`Id`='19185');
UPDATE `creature_template` SET `ScriptName`='npc_silithid_warrior' WHERE (`entry`='134503');
UPDATE `creature_template` SET `ScriptName`='npc_surging_darkness' WHERE (`entry`='135183');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265231', 'spell_void_lash_selector');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('264954', 'spell_titan_spark_aura');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('265061', 'spell_titan_spark_bunny_selector');
UPDATE `creature_template` SET `unit_flags`='768', `flags_extra`='128' WHERE (`entry`='139424');
UPDATE `creature_template` SET `unit_flags`='768' WHERE (`entry`='133492');
UPDATE `creature_template` SET `unit_flags`='768' WHERE (`entry`='141265');