replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','16','233','4773');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','128','230','7953');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','32','229','3690');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','2','231','4752');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','8','225','4753');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','1','224','4732');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','64','228','7954');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','4','226','4772');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','1024','227','20914');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('20','512','232','16280');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','512','272','16280');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','1024','273','20914');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','4','274','4772');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','64','275','7954');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','1','276','4732');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','8','277','4753');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','2','278','4752');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','32','279','3690');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','128','280','7953');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('40','16','281','4773');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('60','690','282','35093');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('60','1101','283','35100');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('70','1101','284','35133');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('70','690','285','35135');
replace into `mail_level_reward` (`level`, `raceMask`, `mailTemplateId`, `senderEntry`) values('77','1791','265','33817');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('87','6529','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('119','15564','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('120','15564','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('180','24132','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('103','11422','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('99','11423','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('104','11422','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('100','11423','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('94','20469','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('93','20469','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('98','13158','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('109','19858','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('113','19697','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('111','19697','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('183','31698','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('118','17685','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('102','17685','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('117','17712','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('161','21216','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('122','21216','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('108','17712','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('224','46875','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('225','46876','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('226','46877','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('227','46879','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('228','46878','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('229','46884','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('230','46883','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('231','46880','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('232','46882','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('233','46881','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('211','37676','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('262','43516','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('266','46708','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('267','46171','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('286','47840','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('287','50435','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('264','44817','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('269','46545','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('270','46544','0','100','0','1','0','1','1',NULL);
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('110','20645','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('236','39317','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('237','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('238','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('239','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('240','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('241','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('242','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('243','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('244','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('245','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('246','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('247','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('248','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('249','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('250','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('251','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('252','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('253','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('254','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('255','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('256','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('257','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('258','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('259','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('260','21746','0','100','0','1','0','1','1','');
replace into `mail_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) values('261','21746','0','100','0','1','0','1','1','');
